pull_request_rules:
  - name: automatic merge dependency updates
    conditions:
      - status-success=build
      - author~=dependabot
      - -files~=^(!?.github/workflows/)
    actions:
      queue:
        name: default
      delete_head_branch: {}
queue_rules:
  - autosquash: true
    autoqueue: true
    name: default
    branch_protection_injection_mode: merge
