pull_request_rules:
  - name: automatic merge dependency updates
    conditions:
      - status-success=build
      - author~=dependabot
      - -files~=^(!?.github/workflows/)
    actions:
      merge:
        method: squash
      delete_head_branch: {}
queue_rules:
  - autoqueue: true
    name: default
    branch_protection_injection_mode: queue
    queue_conditions:
      - and:
          - author = dependabot[bot]
          - check-success = build
